name: Increment Counter

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  increment_counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          release_info=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "Release info: $release_info"
          counter=$(echo "$release_info" | jq -r '.tag_name' | cut -d '.' -f 3)
          echo "Counter: $counter"

      # Get the current counter value from the latest release
      - name: Get current counter
        id: get_counter
        run: |
          counter=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' | cut -d '.' -f 3)
          echo "::set-output name=counter::$((counter + 1))"

      # Update the release tag with the incremented counter value
      - name: Create or update release
        id: create_or_update_release
        uses: actions/create-release@v1
        with:
          tag_name: "v1.2.2.2${{ steps.get_counter.outputs.counter }}"
          release_name: Release 1.2.${{ steps.get_counter.outputs.counter }}
          body: |
            This is release 1.2.${{ steps.get_counter.outputs.counter }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}