name: Example Workflow # 工作流名称

on: # 定义触发条件
  push: # 当push到main分支时触发
    # branches:
    #   - main
  workflow_dispatch: # 或手动触发
    inputs: # 定义输入参数列表
      name-of-var: # 第一个待输入参数
        description: 'Description of this var'
        required: true
        default: 'default string'
      name-of-var-2: # 第二个待输入参数
        description: 'Description of this var2'
        required: false # 可选参数, 可以不输入

env: # 定义环境变量
  HELLO1: world1

jobs: # 定义工作流
  # echo-hello: # 工作流名称
  #   runs-on: ubuntu-latest # 运行环境
  #   steps: # 步骤
  #     - name: Echo hello # 步骤 1 的步骤名称
  #       # 使用 run 关键字执行 shell 命令
  #       run: echo "Hello, ${{ github.event.inputs.name-of-var }}"
  #     - name: Echo hello 2 # 步骤 2 的步骤名称
  #       # run 关键字后加 | 表示多行命令
  #       run: |
  #         HELLO2="Hello, ${{ github.event.inputs.name-of-var-2 }}"
  #         echo $HELLO2
  #         echo $HELLO2 > hello2.txt
  #     - name: upload-artifact # 步骤 3 的步骤名称
  #       # 使用 uses 关键字引用 actions/upload-artifact@v2 动作
  #       # 这个动作会将 hello2.txt 上传到 GitHub Actions 的 Artifacts
  #       uses: actions/upload-artifact@v4
  #       with: # 输入参数列表
  #         name: hello2
  #         path: hello2.txt

  env-var-example:
    runs-on: ubuntu-latest
    # 设置变量
    env: # 定义环境变量
      HELLO2: world2
    # 设置输出
    outputs:
      HELLO7: ${{ steps.set-output.outputs.HELLO5 }}
      HELLO8: ${{ steps.set-output.outputs.HELLO6 }}
      HELLO9: "$HELLO1 world9"
      HELLO10: ${{ steps.set-output.outputs.HELLO5 }} world10
    steps:
      - name: Set env var
        run: |
          echo "HELLO3=world3" >> $GITHUB_ENV
          echo "HELLO4=world4" >> $GITHUB_ENV
      - name: Echo env var
        run: |
          echo $HELLO1
          echo $HELLO2
          echo $HELLO3
          echo $HELLO4
      # echo github context
      - name: Echo github context
        run: node -e "console.log(JSON.stringify(process.env, null, 2))"

      - name: set-output
        id: set-output
        run: |
          HELLO5=world5
          echo "::set-output name=HELLO5::$HELLO5"
          echo "::set-output name=HELLO6::world6"
      - name: use-output
        run: |
          echo ${{ steps.set-output.outputs.HELLO5 }}
          echo ${{ steps.set-output.outputs.HELLO6 }}
      
      - name: use-git-context
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.event_name }}
          echo ${{ github.event.inputs.name-of-var }}
          echo ${{ github.event.inputs.name-of-var-2 }}
  
  use-output:
    needs: env-var-example
    runs-on: ubuntu-latest
    steps:
      - name: Echo output
        run: |
          echo ${{ needs.env-var-example.outputs.HELLO7 }}
          echo ${{ needs.env-var-example.outputs.HELLO8 }}
          echo ${{ needs.env-var-example.outputs.HELLO9 }}
          echo ${{ needs.env-var-example.outputs.HELLO10 }}
  