on:
  workflow_dispatch:
    inputs:
      name-of-var:
        description: 'Description of this var'
        required: true
        default: 'default string'
      name-of-var-2:
        description: 'Description of this var2'
        required: false


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "Hello, ${{ github.event.inputs.message }}"
